sudo: false
matrix:
  allow_failures:
    - os: osx
    - python: 3.8-dev
    - env: TRAVIS_NODE_VERSION=9
  include:
    - language: python
      python: 2.7
      env: TRAVIS_NODE_VERSION=4.9
    - language: python
      python: 3.4
      env: TRAVIS_NODE_VERSION=6.14
    - language: python
      python: 3.5
      env: TRAVIS_NODE_VERSION=8.9
    - language: python
      python: 3.6
      env: TRAVIS_NODE_VERSION=8.11
    - language: python
      python: 3.7
      dist: xenial
      sudo: true
      env: TRAVIS_NODE_VERSION=10
    - language: python
      python: 3.8-dev
      dist: xenial
      sudo: true
      env: TRAVIS_NODE_VERSION=10
    - language: python
      python: pypy
      env: TRAVIS_NODE_VERSION=4.8
    - language: python
      python: pypy3
      env: TRAVIS_NODE_VERSION=6.12
    # test different versions of Node.js on osx
    - language: node_js
      node_js: 4.9
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.4.8
    - language: node_js
      node_js: 6.14
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.5.5
    - language: node_js
      node_js: 8.11
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.6.6
    - language: node_js
      node_js: 10
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.7.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update || brew update ;
      brew install pyenv ;
      brew outdated pyenv || brew upgrade pyenv ;
      pyenv install $TRAVIS_PYTHON_VERSION ;
      pyenv global $TRAVIS_PYTHON_VERSION ;
      eval "$(pyenv init -)" ;
      python --version ;
      python -m pip install --user virtualenv ;
      python -m virtualenv ~/.venv ;
      source ~/.venv/bin/activate ;
    else
      rm -rf ~/.nvm ;
      git clone https://github.com/creationix/nvm.git ~/.nvm ;
      (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` );
      source ~/.nvm/nvm.sh ;
      nvm install "$TRAVIS_NODE_VERSION" ;
    fi
  - node --version
  - npm --version

install:
  - pip install coverage flake8
  # Installing all the packages via pip to ensure the wheels are used,
  # to avoid the failure conditions with using the setup.py scripts that
  # occur on various platforms and configurations.  The -U flag is also
  # used to ensure setuptools is updated.
  - pip install -U calmjs
  - python setup.py develop
script:
  - flake8 setup.py src
  # run the first test without calmjs.dev.
  - python -m unittest calmjs.webpack.tests.make_suite
  # run the real test with all optional dependencies.
  - pip install -e .[dev]
  - coverage run --include=src/* -m unittest calmjs.webpack.tests.make_suite
  - coverage report -m
after_success:
  # only submit coverage when testing under linux.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install coveralls ;
      coveralls ;
    fi
branches:
  only:
    - testing
    - master
    - 1.0.x
    - 1.1.x
